"""initial migration

Revision ID: 640fe90971c0
Revises: 1cb7a2c062cf
Create Date: 2024-05-08 03:17:23.526801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '640fe90971c0'
down_revision: Union[str, None] = '1cb7a2c062cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('task_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'task', ['task_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'task_id')
    # ### end Alembic commands ###
